# Generated by Django 4.2.5 on 2023-10-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='rubrique',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='magazine',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='rubrique',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='podcast',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='rubrique',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='video',
            name='creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='rubrique',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
