# Generated by Django 4.2.5 on 2023-10-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_article_link_magazine_link_podcast_link_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
