# Generated by Django 4.2.5 on 2023-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_article_creation_alter_magazine_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='pdf/publications/magazines/thumbnails/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='pdf/publications/podcasts/thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='pdf/publications/videos/thumbnails/'),
        ),
    ]
