# Generated by Django 4.2.5 on 2023-10-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caterogy', models.CharField(blank=True, max_length=50, null=True)),
                ('sender', models.CharField(blank=True, max_length=50, null=True)),
                ('reciever', models.CharField(blank=True, max_length=100, null=True)),
                ('subjet', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
