# Generated by Django 4.2.5 on 2023-10-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lead_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, default='awaiting', max_length=30),
        ),
    ]
